export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  VIEW_CUSTOMER:"/viewCustomer",
  MY_CALLS:"/myCalls",
  VIEW_CUST:"/viewCust",
  VIEW_CUST_ID:"/viewCust/:id",
  CALL_REMINDER:"/callReminder",

  FORGOT_PASSWORD: "/forgotPassword",
  THANK_YOU: "/thankyou",
  NEW_PASSWORD: "/newPassword",
  HOME: "/home",
  ADMIN_HOME: "/adminHome",
  ADMIN_PENDING_PAYMENTS: "/adminPendingPayments",
  ADMIN_REGISTRATION_REQUESTS: "/adminRegistrationRequests",
  ADMIN_SERVICE_REQUESTS: "/adminServiceRequests",
  ADMIN_PROFESSIONAL_ALLOCATION: "/adminProfessionalAllocation",
  ADMIN_PROFESSIONAL_ALLOCATION_ASSIGN: "/adminProfessionalAllocationAssign",
  ADMIN_PROFESSIONAL_DIRECT_ASSIGN: "/adminProfessionalDirectAssign",
  ADMIN_TIMESHEET_APPROVAL: "/adminTimesheetApproval",
  CLIENT_INVOICES: "/clientInvoices",
  CLIENT_SERVICE_REQUEST_STATUS: "/clientServiceStatus",
  CLIENT_NEW_SERVICE_REQUEST: "/clientNewRequest",
  CLIENT_EDIT_USER: "/editClient",
  PROFESSIONAL: "/professional",
  PROFESSIONAL_TIMESHEET: "/professionalTimeSheet",
  PROFESSIONAL_SALARYSLIP: "/professionalSalarySlip",
  PROFESSIONAL_SERVICE_REQUEST: "/professionalServiceRequests",
  PROFESSIONAL_SERVICE_CALLS: "/professionalServiceCalls",
  PROFESSIONAL_EDIT_USER: "/editProfessional",
};
