export const UserActionTypes = {
  SET_LOGGED_IN_STATUS: "SET_LOGGED_IN_STATUS",
  SET_USER_DATA: "SET_USER_DATA",
  SET_USER_INFO: "SET_USER_INFO",

  // saga types
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
};
